/* automatically generated by rust-bindgen */

pub enum Struct_ub_ctx { }
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ub_result {
    pub qname: *mut ::libc::c_char,
    pub qtype: ::libc::c_int,
    pub qclass: ::libc::c_int,
    pub data: *mut *mut ::libc::c_char,
    pub len: *mut ::libc::c_int,
    pub canonname: *mut ::libc::c_char,
    pub rcode: ::libc::c_int,
    pub answer_packet: *mut ::libc::c_void,
    pub answer_len: ::libc::c_int,
    pub havedata: ::libc::c_int,
    pub nxdomain: ::libc::c_int,
    pub secure: ::libc::c_int,
    pub bogus: ::libc::c_int,
    pub why_bogus: *mut ::libc::c_char,
    pub ttl: ::libc::c_int,
}
impl ::std::clone::Clone for Struct_ub_result {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_ub_result {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ub_callback_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::libc::c_void,
                                               arg2: ::libc::c_int,
                                               arg3: *mut Struct_ub_result)
                              -> ()>;
extern "C" {
    pub fn ub_ctx_create() -> *mut Struct_ub_ctx;
    pub fn ub_ctx_delete(ctx: *mut Struct_ub_ctx) -> ();
    pub fn ub_ctx_set_option(ctx: *mut Struct_ub_ctx,
                             opt: *const ::libc::c_char,
                             val: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_get_option(ctx: *mut Struct_ub_ctx,
                             opt: *const ::libc::c_char,
                             str: *mut *mut ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_config(ctx: *mut Struct_ub_ctx,
                         fname: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_set_fwd(ctx: *mut Struct_ub_ctx,
                          addr: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_resolvconf(ctx: *mut Struct_ub_ctx,
                             fname: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_hosts(ctx: *mut Struct_ub_ctx, fname: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn ub_ctx_add_ta(ctx: *mut Struct_ub_ctx, ta: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn ub_ctx_add_ta_file(ctx: *mut Struct_ub_ctx,
                              fname: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_add_ta_autr(ctx: *mut Struct_ub_ctx,
                              fname: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_trustedkeys(ctx: *mut Struct_ub_ctx,
                              fname: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_debugout(ctx: *mut Struct_ub_ctx, out: *mut ::libc::c_void)
     -> ::libc::c_int;
    pub fn ub_ctx_debuglevel(ctx: *mut Struct_ub_ctx, d: ::libc::c_int)
     -> ::libc::c_int;
    pub fn ub_ctx_async(ctx: *mut Struct_ub_ctx, dothread: ::libc::c_int)
     -> ::libc::c_int;
    pub fn ub_poll(ctx: *mut Struct_ub_ctx) -> ::libc::c_int;
    pub fn ub_wait(ctx: *mut Struct_ub_ctx) -> ::libc::c_int;
    pub fn ub_fd(ctx: *mut Struct_ub_ctx) -> ::libc::c_int;
    pub fn ub_process(ctx: *mut Struct_ub_ctx) -> ::libc::c_int;
    pub fn ub_resolve(ctx: *mut Struct_ub_ctx, name: *const ::libc::c_char,
                      rrtype: ::libc::c_int, rrclass: ::libc::c_int,
                      result: *mut *mut Struct_ub_result) -> ::libc::c_int;
    pub fn ub_resolve_async(ctx: *mut Struct_ub_ctx,
                            name: *const ::libc::c_char,
                            rrtype: ::libc::c_int, rrclass: ::libc::c_int,
                            mydata: *mut ::libc::c_void,
                            callback: ub_callback_t,
                            async_id: *mut ::libc::c_int) -> ::libc::c_int;
    pub fn ub_cancel(ctx: *mut Struct_ub_ctx, async_id: ::libc::c_int)
     -> ::libc::c_int;
    pub fn ub_resolve_free(result: *mut Struct_ub_result) -> ();
    pub fn ub_strerror(err: ::libc::c_int) -> *const ::libc::c_char;
    pub fn ub_ctx_print_local_zones(ctx: *mut Struct_ub_ctx) -> ::libc::c_int;
    pub fn ub_ctx_zone_add(ctx: *mut Struct_ub_ctx,
                           zone_name: *const ::libc::c_char,
                           zone_type: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_zone_remove(ctx: *mut Struct_ub_ctx,
                              zone_name: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn ub_ctx_data_add(ctx: *mut Struct_ub_ctx,
                           data: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_ctx_data_remove(ctx: *mut Struct_ub_ctx,
                              data: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ub_version() -> *const ::libc::c_char;
}
