[package]
name = "unbound"
version = "0.5.0"
authors = ["Andrew Tunnell-Jones <andrew@tj.id.au>"]
license = "BSD-3-Clause"
description = "Wraps libunbound; an implementation of a DNS resolver including cache and DNSSEC validation."
documentation = "https://docs.rs/unbound"
repository = "https://github.com/andrewtj/rust-unbound"
readme = "README.md"
build = "build.rs"
keywords = ["dns", "dnssec"]

[dependencies]
unbound-sys = { version = "0.5", path = "../unbound-sys" }
libc = "0.2"

[build-dependencies]
tempdir = "0.3.5"
gcc = "0.3.51"
