[package]
name = "unbound"
version = "0.2.0"
authors = ["Andrew Tunnell-Jones <andrew@tj.id.au>"]
license = "BSD-3-Clause"
description = "libunbound wrapper"
documentation = "http://www.andrewtj.org/rust-unbound/unbound/"
homepage = "https://github.com/andrewtj/rust-unbound"
repository = "https://github.com/andrewtj/rust-unbound"
readme = "../README.md"
keywords = ["dns", "dnssec"]

[dependencies]
unbound-sys = { version = "0.2", path = "../unbound-sys" }
libc = "0.2"
